#*****************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# make_prj.tcl: Tcl script for re-creating project 'lvcmos_iob_nosem(8)'
#
# Generated by Vivado on Wed Sep 27 21:32:00 -0600 2023
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (make_prj2.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "d:/git/iob/lvcmos_iob_nosem/lvcmos_iob_nosem.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v"
#    "d:/git/iob/lvcmos_iob_nosem/lvcmos_iob_nosem.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/git/iob/hdl/iob_lvcmos_dut_reg_versal.vhd"
#    "D:/git/iob/xdc/constraints_lvcmos_versal.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true

  set files [list \
 "[file normalize "$origin_dir/hdl/iob_lvcmos_dut_reg_versal.vhd"]"\
 "[file normalize "$origin_dir/xdc/constraints_lvcmos_versal.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "lvcmos_iob_nosem"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "make_prj.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-origin_dir_override\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/ws"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./ws -part xcvc1902-vsva2197-1MP-e-S

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
# set_property -name "ip_output_repo" -value "$orig_proj_dir/lvcmos_iob_nosem.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvc1902-vsva2197-1MP-e-S" -objects $obj
set_property -name "sim.central_dir" -value "$orig_proj_dir/lvcmos_iob_nosem.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "1" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "1" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "1" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "1" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/hdl/iob_lvcmos_dut_reg_versal.vhd"] \
]
add_files -norecurse -fileset $obj $files



# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hdl/iob_lvcmos_dut_reg_versal.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/xdc/constraints_lvcmos_versal.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/xdc/constraints_lvcmos_versal.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcvc1902-vsva2197-1MP-e-S" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj



# Set 'utils_1' fileset file properties for remote files
# None





# Adding sources referenced in BDs, if not already added
if { [get_files iob_lvcmos_dut_reg_versal.vhd] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/hdl/iob_lvcmos_dut_reg_versal.vhd
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# iob_lvcmos_dut_reg



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:versal_cips:3.2\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  iob_lvcmos_dut_reg\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set df_0000_n [ create_bd_port -dir O df_0000_n ]
  set df_0000_p [ create_bd_port -dir O df_0000_p ]
  set df_0001_n [ create_bd_port -dir I df_0001_n ]
  set df_0001_p [ create_bd_port -dir O df_0001_p ]
  set df_0002_n [ create_bd_port -dir I df_0002_n ]
  set df_0002_p [ create_bd_port -dir O df_0002_p ]
  set df_0004_n [ create_bd_port -dir O df_0004_n ]
  set df_0004_p [ create_bd_port -dir O df_0004_p ]
  set df_0005_n [ create_bd_port -dir O df_0005_n ]
  set df_0005_p [ create_bd_port -dir O df_0005_p ]
  set df_0007_n [ create_bd_port -dir I df_0007_n ]
  set df_0007_p [ create_bd_port -dir O df_0007_p ]
  set df_0008_n [ create_bd_port -dir I df_0008_n ]
  set df_0008_p [ create_bd_port -dir O df_0008_p ]
  set df_0010_n [ create_bd_port -dir O df_0010_n ]
  set df_0010_p [ create_bd_port -dir O df_0010_p ]
  set df_0011_n [ create_bd_port -dir O df_0011_n ]
  set df_0011_p [ create_bd_port -dir O df_0011_p ]
  set df_0012_n [ create_bd_port -dir I df_0012_n ]
  set df_0012_p [ create_bd_port -dir O df_0012_p ]
  set df_0013_n [ create_bd_port -dir O df_0013_n ]
  set df_0013_p [ create_bd_port -dir O df_0013_p ]
  set df_0014_n [ create_bd_port -dir I df_0014_n ]
  set df_0014_p [ create_bd_port -dir O df_0014_p ]
  set df_0016_n [ create_bd_port -dir O df_0016_n ]
  set df_0016_p [ create_bd_port -dir O df_0016_p ]
  set df_0017_n [ create_bd_port -dir I df_0017_n ]
  set df_0017_p [ create_bd_port -dir O df_0017_p ]
  set df_0018_n [ create_bd_port -dir I df_0018_n ]
  set df_0018_p [ create_bd_port -dir O df_0018_p ]
  set df_0019_n [ create_bd_port -dir I df_0019_n ]
  set df_0019_p [ create_bd_port -dir O df_0019_p ]
  set df_0020_n [ create_bd_port -dir O df_0020_n ]
  set df_0020_p [ create_bd_port -dir O df_0020_p ]
  set df_0022_n [ create_bd_port -dir O df_0022_n ]
  set df_0022_p [ create_bd_port -dir O df_0022_p ]
  set df_0023_n [ create_bd_port -dir O df_0023_n ]
  set df_0023_p [ create_bd_port -dir O df_0023_p ]
  set df_0028_n [ create_bd_port -dir I df_0028_n ]
  set df_0028_p [ create_bd_port -dir O df_0028_p ]
  set df_0029_n [ create_bd_port -dir I df_0029_n ]
  set df_0029_p [ create_bd_port -dir O df_0029_p ]
  set df_0046_n [ create_bd_port -dir O df_0046_n ]
  set df_0046_p [ create_bd_port -dir O df_0046_p ]
  set df_0048_n [ create_bd_port -dir O df_0048_n ]
  set df_0048_p [ create_bd_port -dir O df_0048_p ]
  set df_0049_n [ create_bd_port -dir I df_0049_n ]
  set df_0049_p [ create_bd_port -dir O df_0049_p ]
  set df_0050_n [ create_bd_port -dir O df_0050_n ]
  set df_0050_p [ create_bd_port -dir O df_0050_p ]
  set df_0051_n [ create_bd_port -dir O df_0051_n ]
  set df_0051_p [ create_bd_port -dir O df_0051_p ]
  set df_0052_n [ create_bd_port -dir I df_0052_n ]
  set df_0052_p [ create_bd_port -dir O df_0052_p ]
  set df_0053_n [ create_bd_port -dir O df_0053_n ]
  set df_0053_p [ create_bd_port -dir O df_0053_p ]
  set df_0056_n [ create_bd_port -dir I df_0056_n ]
  set df_0056_p [ create_bd_port -dir O df_0056_p ]
  set df_0057_n [ create_bd_port -dir O df_0057_n ]
  set df_0057_p [ create_bd_port -dir O df_0057_p ]
  set df_0059_n [ create_bd_port -dir I df_0059_n ]
  set df_0059_p [ create_bd_port -dir O df_0059_p ]
  set df_0092_n [ create_bd_port -dir O df_0092_n ]
  set df_0092_p [ create_bd_port -dir O df_0092_p ]
  set df_0095_n [ create_bd_port -dir I df_0095_n ]
  set df_0095_p [ create_bd_port -dir O df_0095_p ]
  set df_0099_n [ create_bd_port -dir O df_0099_n ]
  set df_0099_p [ create_bd_port -dir O df_0099_p ]
  set df_i_n_5 [ create_bd_port -dir I df_i_n_5 ]
  set df_i_n_10 [ create_bd_port -dir O df_i_n_10 ]
  set df_i_n_12 [ create_bd_port -dir I df_i_n_12 ]
  set df_i_n_15 [ create_bd_port -dir O df_i_n_15 ]
  set df_i_n_16 [ create_bd_port -dir I df_i_n_16 ]
  set df_i_n_17 [ create_bd_port -dir O df_i_n_17 ]
  set df_i_n_20 [ create_bd_port -dir I df_i_n_20 ]
  set df_i_n_54 [ create_bd_port -dir I df_i_n_54 ]
  set df_i_n_80 [ create_bd_port -dir I df_i_n_80 ]
  set df_i_p_5 [ create_bd_port -dir O df_i_p_5 ]
  set df_i_p_10 [ create_bd_port -dir O df_i_p_10 ]
  set df_i_p_12 [ create_bd_port -dir O df_i_p_12 ]
  set df_i_p_15 [ create_bd_port -dir O df_i_p_15 ]
  set df_i_p_16 [ create_bd_port -dir O df_i_p_16 ]
  set df_i_p_17 [ create_bd_port -dir O df_i_p_17 ]
  set df_i_p_20 [ create_bd_port -dir O df_i_p_20 ]
  set df_i_p_54 [ create_bd_port -dir O df_i_p_54 ]
  set df_i_p_80 [ create_bd_port -dir I df_i_p_80 ]
  set df_o_n_1 [ create_bd_port -dir O df_o_n_1 ]
  set df_o_n_2 [ create_bd_port -dir I df_o_n_2 ]
  set df_o_n_5 [ create_bd_port -dir I df_o_n_5 ]
  set df_o_n_6 [ create_bd_port -dir O df_o_n_6 ]
  set df_o_n_7 [ create_bd_port -dir I df_o_n_7 ]
  set df_o_n_9 [ create_bd_port -dir I df_o_n_9 ]
  set df_o_n_10 [ create_bd_port -dir O df_o_n_10 ]
  set df_o_n_11 [ create_bd_port -dir I df_o_n_11 ]
  set df_o_n_12 [ create_bd_port -dir O df_o_n_12 ]
  set df_o_n_14 [ create_bd_port -dir O df_o_n_14 ]
  set df_o_n_15 [ create_bd_port -dir I df_o_n_15 ]
  set df_o_n_16 [ create_bd_port -dir O df_o_n_16 ]
  set df_o_n_17 [ create_bd_port -dir I df_o_n_17 ]
  set df_o_n_19 [ create_bd_port -dir I df_o_n_19 ]
  set df_o_n_20 [ create_bd_port -dir O df_o_n_20 ]
  set df_o_n_57 [ create_bd_port -dir O df_o_n_57 ]
  set df_o_p_1 [ create_bd_port -dir O df_o_p_1 ]
  set df_o_p_2 [ create_bd_port -dir O df_o_p_2 ]
  set df_o_p_5 [ create_bd_port -dir O df_o_p_5 ]
  set df_o_p_6 [ create_bd_port -dir O df_o_p_6 ]
  set df_o_p_7 [ create_bd_port -dir O df_o_p_7 ]
  set df_o_p_9 [ create_bd_port -dir O df_o_p_9 ]
  set df_o_p_10 [ create_bd_port -dir O df_o_p_10 ]
  set df_o_p_11 [ create_bd_port -dir O df_o_p_11 ]
  set df_o_p_12 [ create_bd_port -dir O df_o_p_12 ]
  set df_o_p_14 [ create_bd_port -dir O df_o_p_14 ]
  set df_o_p_15 [ create_bd_port -dir O df_o_p_15 ]
  set df_o_p_16 [ create_bd_port -dir O df_o_p_16 ]
  set df_o_p_17 [ create_bd_port -dir O df_o_p_17 ]
  set df_o_p_19 [ create_bd_port -dir O df_o_p_19 ]
  set df_o_p_20 [ create_bd_port -dir O df_o_p_20 ]
  set df_o_p_57 [ create_bd_port -dir O df_o_p_57 ]

  # Create instance: XRTC_CIPS_noSem, and set properties
  set XRTC_CIPS_noSem [ create_bd_cell -type ip -vlnv xilinx.com:ip:versal_cips:3.2 XRTC_CIPS_noSem ]
  set_property -dict [ list \
   CONFIG.BOOT_MODE {Custom} \
   CONFIG.DEBUG_MODE {Custom} \
   CONFIG.IO_CONFIG_MODE {Custom} \
   CONFIG.PS_PMC_CONFIG {\
     BOOT_MODE {Custom}\
     DEBUG_MODE {Custom}\
     IO_CONFIG_MODE {Custom}\
     PMC_BANK_0_IO_STANDARD {LVCMOS3.3}\
     PMC_BANK_1_IO_STANDARD {LVCMOS3.3}\
     PMC_QSPI_PERIPHERAL_ENABLE {0}\
     PMC_QSPI_PERIPHERAL_MODE {Single}\
     PMC_REF_CLK_FREQMHZ {50.0}\
     PMC_SMAP_PERIPHERAL {{ENABLE 1} {IO {32 Bit}}}\
     PS_BANK_2_IO_STANDARD {LVCMOS3.3}\
     PS_BANK_3_IO_STANDARD {LVCMOS3.3}\
     PS_HSDP_INGRESS_TRAFFIC {JTAG}\
     PS_HSDP_MODE {NONE}\
     PS_UART0_BAUD_RATE {115200}\
     PS_UART0_PERIPHERAL {{ENABLE 1} {IO {PMC_MIO 26 .. 27}}}\
     PS_UART1_PERIPHERAL {{ENABLE 0} {IO {PMC_MIO 4 .. 5}}}\
     SEM_MEM_ENABLE_SCAN_AFTER {0}\
     SEM_MEM_SCAN {0}\
     SMON_ALARMS {Set_Alarms_On}\
     SMON_ENABLE_TEMP_AVERAGING {0}\
     SMON_TEMP_AVERAGING_SAMPLES {0}\
   } \
   CONFIG.PS_PMC_CONFIG_APPLIED {1} \
 ] $XRTC_CIPS_noSem

  # Create instance: iob_lvcmos_dut_reg_0, and set properties
  set block_name iob_lvcmos_dut_reg
  set block_cell_name iob_lvcmos_dut_reg_0
  if { [catch {set iob_lvcmos_dut_reg_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $iob_lvcmos_dut_reg_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create port connections
  connect_bd_net -net df_0001_n_1 [get_bd_ports df_0001_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0001_n]
  connect_bd_net -net df_0002_n_1 [get_bd_ports df_0002_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0002_n]
  connect_bd_net -net df_0007_n_1 [get_bd_ports df_0007_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0007_n]
  connect_bd_net -net df_0008_n_1 [get_bd_ports df_0008_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0008_n]
  connect_bd_net -net df_0012_n_1 [get_bd_ports df_0012_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0012_n]
  connect_bd_net -net df_0014_n_1 [get_bd_ports df_0014_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0014_n]
  connect_bd_net -net df_0017_n_1 [get_bd_ports df_0017_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0017_n]
  connect_bd_net -net df_0018_n_1 [get_bd_ports df_0018_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0018_n]
  connect_bd_net -net df_0019_n_1 [get_bd_ports df_0019_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0019_n]
  connect_bd_net -net df_0028_n_1 [get_bd_ports df_0028_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0028_n]
  connect_bd_net -net df_0029_n_1 [get_bd_ports df_0029_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0029_n]
  connect_bd_net -net df_0049_n_1 [get_bd_ports df_0049_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0049_n]
  connect_bd_net -net df_0052_n_1 [get_bd_ports df_0052_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0052_n]
  connect_bd_net -net df_0056_n_1 [get_bd_ports df_0056_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0056_n]
  connect_bd_net -net df_0059_n_1 [get_bd_ports df_0059_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0059_n]
  connect_bd_net -net df_0095_n_1 [get_bd_ports df_0095_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0095_n]
  connect_bd_net -net df_i_n_12_1 [get_bd_ports df_i_n_12] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_12]
  connect_bd_net -net df_i_n_16_1 [get_bd_ports df_i_n_16] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_16]
  connect_bd_net -net df_i_n_20_1 [get_bd_ports df_i_n_20] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_20]
  connect_bd_net -net df_i_n_54_1 [get_bd_ports df_i_n_54] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_54]
  connect_bd_net -net df_i_n_5_1 [get_bd_ports df_i_n_5] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_5]
  connect_bd_net -net df_i_n_80_1 [get_bd_ports df_i_n_80] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_80]
  connect_bd_net -net df_i_p_80_1 [get_bd_ports df_i_p_80] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_80]
  connect_bd_net -net df_o_n_11_1 [get_bd_ports df_o_n_11] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_11]
  connect_bd_net -net df_o_n_15_1 [get_bd_ports df_o_n_15] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_15]
  connect_bd_net -net df_o_n_17_1 [get_bd_ports df_o_n_17] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_17]
  connect_bd_net -net df_o_n_19_1 [get_bd_ports df_o_n_19] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_19]
  connect_bd_net -net df_o_n_2_1 [get_bd_ports df_o_n_2] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_2]
  connect_bd_net -net df_o_n_5_1 [get_bd_ports df_o_n_5] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_5]
  connect_bd_net -net df_o_n_7_1 [get_bd_ports df_o_n_7] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_7]
  connect_bd_net -net df_o_n_9_1 [get_bd_ports df_o_n_9] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_9]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0000_n [get_bd_ports df_0000_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0000_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0000_p [get_bd_ports df_0000_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0000_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0001_p [get_bd_ports df_0001_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0001_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0002_p [get_bd_ports df_0002_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0002_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0004_n [get_bd_ports df_0004_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0004_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0004_p [get_bd_ports df_0004_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0004_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0005_n [get_bd_ports df_0005_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0005_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0005_p [get_bd_ports df_0005_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0005_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0007_p [get_bd_ports df_0007_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0007_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0008_p [get_bd_ports df_0008_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0008_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0010_n [get_bd_ports df_0010_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0010_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0010_p [get_bd_ports df_0010_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0010_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0011_n [get_bd_ports df_0011_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0011_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0011_p [get_bd_ports df_0011_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0011_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0012_p [get_bd_ports df_0012_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0012_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0013_n [get_bd_ports df_0013_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0013_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0013_p [get_bd_ports df_0013_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0013_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0014_p [get_bd_ports df_0014_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0014_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0016_n [get_bd_ports df_0016_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0016_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0016_p [get_bd_ports df_0016_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0016_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0017_p [get_bd_ports df_0017_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0017_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0018_p [get_bd_ports df_0018_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0018_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0019_p [get_bd_ports df_0019_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0019_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0020_n [get_bd_ports df_0020_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0020_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0020_p [get_bd_ports df_0020_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0020_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0022_n [get_bd_ports df_0022_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0022_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0022_p [get_bd_ports df_0022_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0022_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0023_n [get_bd_ports df_0023_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0023_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0023_p [get_bd_ports df_0023_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0023_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0028_p [get_bd_ports df_0028_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0028_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0029_p [get_bd_ports df_0029_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0029_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0046_n [get_bd_ports df_0046_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0046_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0046_p [get_bd_ports df_0046_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0046_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0048_n [get_bd_ports df_0048_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0048_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0048_p [get_bd_ports df_0048_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0048_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0049_p [get_bd_ports df_0049_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0049_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0050_n [get_bd_ports df_0050_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0050_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0050_p [get_bd_ports df_0050_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0050_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0051_n [get_bd_ports df_0051_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0051_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0051_p [get_bd_ports df_0051_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0051_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0052_p [get_bd_ports df_0052_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0052_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0053_n [get_bd_ports df_0053_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0053_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0053_p [get_bd_ports df_0053_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0053_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0056_p [get_bd_ports df_0056_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0056_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0057_n [get_bd_ports df_0057_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0057_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0057_p [get_bd_ports df_0057_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0057_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0059_p [get_bd_ports df_0059_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0059_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0092_n [get_bd_ports df_0092_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0092_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0092_p [get_bd_ports df_0092_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0092_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0095_p [get_bd_ports df_0095_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0095_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0099_n [get_bd_ports df_0099_n] [get_bd_pins iob_lvcmos_dut_reg_0/df_0099_n]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_0099_p [get_bd_ports df_0099_p] [get_bd_pins iob_lvcmos_dut_reg_0/df_0099_p]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_n_10 [get_bd_ports df_i_n_10] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_10]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_n_15 [get_bd_ports df_i_n_15] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_15]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_n_17 [get_bd_ports df_i_n_17] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_n_17]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_5 [get_bd_ports df_i_p_5] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_5]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_10 [get_bd_ports df_i_p_10] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_10]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_12 [get_bd_ports df_i_p_12] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_12]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_15 [get_bd_ports df_i_p_15] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_15]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_16 [get_bd_ports df_i_p_16] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_16]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_17 [get_bd_ports df_i_p_17] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_17]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_20 [get_bd_ports df_i_p_20] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_20]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_i_p_54 [get_bd_ports df_i_p_54] [get_bd_pins iob_lvcmos_dut_reg_0/df_i_p_54]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_1 [get_bd_ports df_o_n_1] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_1]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_6 [get_bd_ports df_o_n_6] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_6]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_10 [get_bd_ports df_o_n_10] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_10]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_12 [get_bd_ports df_o_n_12] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_12]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_14 [get_bd_ports df_o_n_14] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_14]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_16 [get_bd_ports df_o_n_16] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_16]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_20 [get_bd_ports df_o_n_20] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_20]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_n_57 [get_bd_ports df_o_n_57] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_n_57]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_1 [get_bd_ports df_o_p_1] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_1]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_2 [get_bd_ports df_o_p_2] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_2]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_5 [get_bd_ports df_o_p_5] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_5]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_6 [get_bd_ports df_o_p_6] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_6]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_7 [get_bd_ports df_o_p_7] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_7]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_9 [get_bd_ports df_o_p_9] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_9]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_10 [get_bd_ports df_o_p_10] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_10]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_11 [get_bd_ports df_o_p_11] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_11]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_12 [get_bd_ports df_o_p_12] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_12]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_14 [get_bd_ports df_o_p_14] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_14]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_15 [get_bd_ports df_o_p_15] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_15]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_16 [get_bd_ports df_o_p_16] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_16]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_17 [get_bd_ports df_o_p_17] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_17]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_19 [get_bd_ports df_o_p_19] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_19]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_20 [get_bd_ports df_o_p_20] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_20]
  connect_bd_net -net iob_lvcmos_dut_reg_0_df_o_p_57 [get_bd_ports df_o_p_57] [get_bd_pins iob_lvcmos_dut_reg_0/df_o_p_57]

  # Create address segments

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.804061",
   "Default View_TopLeft":"-418,0",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0r6  2020-01-29 bk=1.5227 VDI=41 GEI=36 GUI=JA:10.0 non-TLS-threadsafe
#  -string -flagsOSRD
preplace port port-id_df_0000_n -pg 1 -lvl 3 -x 670 -y 770 -defaultsOSRD
preplace port port-id_df_0000_p -pg 1 -lvl 3 -x 670 -y 790 -defaultsOSRD
preplace port port-id_df_0001_n -pg 1 -lvl 0 -x 0 -y 950 -defaultsOSRD
preplace port port-id_df_0001_p -pg 1 -lvl 3 -x 670 -y 810 -defaultsOSRD
preplace port port-id_df_0002_n -pg 1 -lvl 0 -x 0 -y 1150 -defaultsOSRD
preplace port port-id_df_0002_p -pg 1 -lvl 3 -x 670 -y 1410 -defaultsOSRD
preplace port port-id_df_0004_n -pg 1 -lvl 3 -x 670 -y 1430 -defaultsOSRD
preplace port port-id_df_0004_p -pg 1 -lvl 3 -x 670 -y 1450 -defaultsOSRD
preplace port port-id_df_0005_n -pg 1 -lvl 3 -x 670 -y 830 -defaultsOSRD
preplace port port-id_df_0005_p -pg 1 -lvl 3 -x 670 -y 850 -defaultsOSRD
preplace port port-id_df_0007_n -pg 1 -lvl 0 -x 0 -y 1170 -defaultsOSRD
preplace port port-id_df_0007_p -pg 1 -lvl 3 -x 670 -y 1470 -defaultsOSRD
preplace port port-id_df_0008_n -pg 1 -lvl 0 -x 0 -y 970 -defaultsOSRD
preplace port port-id_df_0008_p -pg 1 -lvl 3 -x 670 -y 870 -defaultsOSRD
preplace port port-id_df_0010_n -pg 1 -lvl 3 -x 670 -y 1490 -defaultsOSRD
preplace port port-id_df_0010_p -pg 1 -lvl 3 -x 670 -y 1510 -defaultsOSRD
preplace port port-id_df_0011_n -pg 1 -lvl 3 -x 670 -y 890 -defaultsOSRD
preplace port port-id_df_0011_p -pg 1 -lvl 3 -x 670 -y 910 -defaultsOSRD
preplace port port-id_df_0012_n -pg 1 -lvl 0 -x 0 -y 990 -defaultsOSRD
preplace port port-id_df_0012_p -pg 1 -lvl 3 -x 670 -y 930 -defaultsOSRD
preplace port port-id_df_0013_n -pg 1 -lvl 3 -x 670 -y 950 -defaultsOSRD
preplace port port-id_df_0013_p -pg 1 -lvl 3 -x 670 -y 970 -defaultsOSRD
preplace port port-id_df_0014_n -pg 1 -lvl 0 -x 0 -y 1190 -defaultsOSRD
preplace port port-id_df_0014_p -pg 1 -lvl 3 -x 670 -y 1530 -defaultsOSRD
preplace port port-id_df_0016_n -pg 1 -lvl 3 -x 670 -y 1550 -defaultsOSRD
preplace port port-id_df_0016_p -pg 1 -lvl 3 -x 670 -y 1570 -defaultsOSRD
preplace port port-id_df_0017_n -pg 1 -lvl 0 -x 0 -y 1010 -defaultsOSRD
preplace port port-id_df_0017_p -pg 1 -lvl 3 -x 670 -y 990 -defaultsOSRD
preplace port port-id_df_0018_n -pg 1 -lvl 0 -x 0 -y 1210 -defaultsOSRD
preplace port port-id_df_0018_p -pg 1 -lvl 3 -x 670 -y 1590 -defaultsOSRD
preplace port port-id_df_0019_n -pg 1 -lvl 0 -x 0 -y 1330 -defaultsOSRD
preplace port port-id_df_0019_p -pg 1 -lvl 3 -x 670 -y 1830 -defaultsOSRD
preplace port port-id_df_0020_n -pg 1 -lvl 3 -x 670 -y 1850 -defaultsOSRD
preplace port port-id_df_0020_p -pg 1 -lvl 3 -x 670 -y 1870 -defaultsOSRD
preplace port port-id_df_0022_n -pg 1 -lvl 3 -x 670 -y 1610 -defaultsOSRD
preplace port port-id_df_0022_p -pg 1 -lvl 3 -x 670 -y 1630 -defaultsOSRD
preplace port port-id_df_0023_n -pg 1 -lvl 3 -x 670 -y 1010 -defaultsOSRD
preplace port port-id_df_0023_p -pg 1 -lvl 3 -x 670 -y 1030 -defaultsOSRD
preplace port port-id_df_0028_n -pg 1 -lvl 0 -x 0 -y 1030 -defaultsOSRD
preplace port port-id_df_0028_p -pg 1 -lvl 3 -x 670 -y 1050 -defaultsOSRD
preplace port port-id_df_0029_n -pg 1 -lvl 0 -x 0 -y 1230 -defaultsOSRD
preplace port port-id_df_0029_p -pg 1 -lvl 3 -x 670 -y 1650 -defaultsOSRD
preplace port port-id_df_0046_n -pg 1 -lvl 3 -x 670 -y 1070 -defaultsOSRD
preplace port port-id_df_0046_p -pg 1 -lvl 3 -x 670 -y 1090 -defaultsOSRD
preplace port port-id_df_0048_n -pg 1 -lvl 3 -x 670 -y 1670 -defaultsOSRD
preplace port port-id_df_0048_p -pg 1 -lvl 3 -x 670 -y 1690 -defaultsOSRD
preplace port port-id_df_0049_n -pg 1 -lvl 0 -x 0 -y 1250 -defaultsOSRD
preplace port port-id_df_0049_p -pg 1 -lvl 3 -x 670 -y 1710 -defaultsOSRD
preplace port port-id_df_0050_n -pg 1 -lvl 3 -x 670 -y 1730 -defaultsOSRD
preplace port port-id_df_0050_p -pg 1 -lvl 3 -x 670 -y 1750 -defaultsOSRD
preplace port port-id_df_0051_n -pg 1 -lvl 3 -x 670 -y 270 -defaultsOSRD
preplace port port-id_df_0051_p -pg 1 -lvl 3 -x 670 -y 290 -defaultsOSRD
preplace port port-id_df_0052_n -pg 1 -lvl 0 -x 0 -y 770 -defaultsOSRD
preplace port port-id_df_0052_p -pg 1 -lvl 3 -x 670 -y 310 -defaultsOSRD
preplace port port-id_df_0053_n -pg 1 -lvl 3 -x 670 -y 330 -defaultsOSRD
preplace port port-id_df_0053_p -pg 1 -lvl 3 -x 670 -y 350 -defaultsOSRD
preplace port port-id_df_0056_n -pg 1 -lvl 0 -x 0 -y 790 -defaultsOSRD
preplace port port-id_df_0056_p -pg 1 -lvl 3 -x 670 -y 370 -defaultsOSRD
preplace port port-id_df_0057_n -pg 1 -lvl 3 -x 670 -y 390 -defaultsOSRD
preplace port port-id_df_0057_p -pg 1 -lvl 3 -x 670 -y 410 -defaultsOSRD
preplace port port-id_df_0059_n -pg 1 -lvl 0 -x 0 -y 810 -defaultsOSRD
preplace port port-id_df_0059_p -pg 1 -lvl 3 -x 670 -y 430 -defaultsOSRD
preplace port port-id_df_0092_n -pg 1 -lvl 3 -x 670 -y 450 -defaultsOSRD
preplace port port-id_df_0092_p -pg 1 -lvl 3 -x 670 -y 470 -defaultsOSRD
preplace port port-id_df_0095_n -pg 1 -lvl 0 -x 0 -y 830 -defaultsOSRD
preplace port port-id_df_0095_p -pg 1 -lvl 3 -x 670 -y 490 -defaultsOSRD
preplace port port-id_df_0099_n -pg 1 -lvl 3 -x 670 -y 510 -defaultsOSRD
preplace port port-id_df_0099_p -pg 1 -lvl 3 -x 670 -y 530 -defaultsOSRD
preplace port port-id_df_i_n_5 -pg 1 -lvl 0 -x 0 -y 870 -defaultsOSRD
preplace port port-id_df_i_n_10 -pg 1 -lvl 3 -x 670 -y 590 -defaultsOSRD
preplace port port-id_df_i_n_12 -pg 1 -lvl 0 -x 0 -y 890 -defaultsOSRD
preplace port port-id_df_i_n_15 -pg 1 -lvl 3 -x 670 -y 650 -defaultsOSRD
preplace port port-id_df_i_n_16 -pg 1 -lvl 0 -x 0 -y 910 -defaultsOSRD
preplace port port-id_df_i_n_17 -pg 1 -lvl 3 -x 670 -y 710 -defaultsOSRD
preplace port port-id_df_i_n_20 -pg 1 -lvl 0 -x 0 -y 710 -defaultsOSRD
preplace port port-id_df_i_n_54 -pg 1 -lvl 0 -x 0 -y 1270 -defaultsOSRD
preplace port port-id_df_i_n_80 -pg 1 -lvl 0 -x 0 -y 1290 -defaultsOSRD
preplace port port-id_df_i_p_5 -pg 1 -lvl 3 -x 670 -y 570 -defaultsOSRD
preplace port port-id_df_i_p_10 -pg 1 -lvl 3 -x 670 -y 610 -defaultsOSRD
preplace port port-id_df_i_p_12 -pg 1 -lvl 3 -x 670 -y 630 -defaultsOSRD
preplace port port-id_df_i_p_15 -pg 1 -lvl 3 -x 670 -y 670 -defaultsOSRD
preplace port port-id_df_i_p_16 -pg 1 -lvl 3 -x 670 -y 690 -defaultsOSRD
preplace port port-id_df_i_p_17 -pg 1 -lvl 3 -x 670 -y 730 -defaultsOSRD
preplace port port-id_df_i_p_20 -pg 1 -lvl 3 -x 670 -y 130 -defaultsOSRD
preplace port port-id_df_i_p_54 -pg 1 -lvl 3 -x 670 -y 1770 -defaultsOSRD
preplace port port-id_df_i_p_80 -pg 1 -lvl 0 -x 0 -y 1310 -defaultsOSRD
preplace port port-id_df_o_n_1 -pg 1 -lvl 3 -x 670 -y 150 -defaultsOSRD
preplace port port-id_df_o_n_2 -pg 1 -lvl 0 -x 0 -y 1050 -defaultsOSRD
preplace port port-id_df_o_n_5 -pg 1 -lvl 0 -x 0 -y 930 -defaultsOSRD
preplace port port-id_df_o_n_6 -pg 1 -lvl 3 -x 670 -y 1130 -defaultsOSRD
preplace port port-id_df_o_n_7 -pg 1 -lvl 0 -x 0 -y 1070 -defaultsOSRD
preplace port port-id_df_o_n_9 -pg 1 -lvl 0 -x 0 -y 730 -defaultsOSRD
preplace port port-id_df_o_n_10 -pg 1 -lvl 3 -x 670 -y 1190 -defaultsOSRD
preplace port port-id_df_o_n_11 -pg 1 -lvl 0 -x 0 -y 1090 -defaultsOSRD
preplace port port-id_df_o_n_12 -pg 1 -lvl 3 -x 670 -y 1250 -defaultsOSRD
preplace port port-id_df_o_n_14 -pg 1 -lvl 3 -x 670 -y 210 -defaultsOSRD
preplace port port-id_df_o_n_15 -pg 1 -lvl 0 -x 0 -y 1110 -defaultsOSRD
preplace port port-id_df_o_n_16 -pg 1 -lvl 3 -x 670 -y 1310 -defaultsOSRD
preplace port port-id_df_o_n_17 -pg 1 -lvl 0 -x 0 -y 1130 -defaultsOSRD
preplace port port-id_df_o_n_19 -pg 1 -lvl 0 -x 0 -y 750 -defaultsOSRD
preplace port port-id_df_o_n_20 -pg 1 -lvl 3 -x 670 -y 1370 -defaultsOSRD
preplace port port-id_df_o_n_57 -pg 1 -lvl 3 -x 670 -y 1790 -defaultsOSRD
preplace port port-id_df_o_p_1 -pg 1 -lvl 3 -x 670 -y 170 -defaultsOSRD
preplace port port-id_df_o_p_2 -pg 1 -lvl 3 -x 670 -y 1110 -defaultsOSRD
preplace port port-id_df_o_p_5 -pg 1 -lvl 3 -x 670 -y 750 -defaultsOSRD
preplace port port-id_df_o_p_6 -pg 1 -lvl 3 -x 670 -y 1150 -defaultsOSRD
preplace port port-id_df_o_p_7 -pg 1 -lvl 3 -x 670 -y 1170 -defaultsOSRD
preplace port port-id_df_o_p_9 -pg 1 -lvl 3 -x 670 -y 190 -defaultsOSRD
preplace port port-id_df_o_p_10 -pg 1 -lvl 3 -x 670 -y 1210 -defaultsOSRD
preplace port port-id_df_o_p_11 -pg 1 -lvl 3 -x 670 -y 1230 -defaultsOSRD
preplace port port-id_df_o_p_12 -pg 1 -lvl 3 -x 670 -y 1270 -defaultsOSRD
preplace port port-id_df_o_p_14 -pg 1 -lvl 3 -x 670 -y 230 -defaultsOSRD
preplace port port-id_df_o_p_15 -pg 1 -lvl 3 -x 670 -y 1290 -defaultsOSRD
preplace port port-id_df_o_p_16 -pg 1 -lvl 3 -x 670 -y 1330 -defaultsOSRD
preplace port port-id_df_o_p_17 -pg 1 -lvl 3 -x 670 -y 1350 -defaultsOSRD
preplace port port-id_df_o_p_19 -pg 1 -lvl 3 -x 670 -y 250 -defaultsOSRD
preplace port port-id_df_o_p_20 -pg 1 -lvl 3 -x 670 -y 1390 -defaultsOSRD
preplace port port-id_df_o_p_57 -pg 1 -lvl 3 -x 670 -y 1810 -defaultsOSRD
preplace inst XRTC_CIPS_noSem -pg 1 -lvl 2 -x 460 -y 60 -defaultsOSRD
preplace inst iob_lvcmos_dut_reg_0 -pg 1 -lvl 1 -x 140 -y 1020 -defaultsOSRD
preplace netloc df_0001_n_1 1 0 1 NJ 950
preplace netloc df_0002_n_1 1 0 1 NJ 1150
preplace netloc df_0007_n_1 1 0 1 NJ 1170
preplace netloc df_0008_n_1 1 0 1 NJ 970
preplace netloc df_0012_n_1 1 0 1 NJ 990
preplace netloc df_0014_n_1 1 0 1 NJ 1190
preplace netloc df_0017_n_1 1 0 1 NJ 1010
preplace netloc df_0018_n_1 1 0 1 NJ 1210
preplace netloc df_0019_n_1 1 0 1 NJ 1330
preplace netloc df_0028_n_1 1 0 1 NJ 1030
preplace netloc df_0029_n_1 1 0 1 NJ 1230
preplace netloc df_0049_n_1 1 0 1 NJ 1250
preplace netloc df_0052_n_1 1 0 1 NJ 770
preplace netloc df_0056_n_1 1 0 1 NJ 790
preplace netloc df_0059_n_1 1 0 1 NJ 810
preplace netloc df_0095_n_1 1 0 1 NJ 830
preplace netloc df_i_n_12_1 1 0 1 NJ 890
preplace netloc df_i_n_16_1 1 0 1 NJ 910
preplace netloc df_i_n_20_1 1 0 1 NJ 710
preplace netloc df_i_n_54_1 1 0 1 NJ 1270
preplace netloc df_i_n_5_1 1 0 1 NJ 870
preplace netloc df_i_n_80_1 1 0 1 NJ 1290
preplace netloc df_i_p_80_1 1 0 1 NJ 1310
preplace netloc df_o_n_11_1 1 0 1 NJ 1090
preplace netloc df_o_n_15_1 1 0 1 NJ 1110
preplace netloc df_o_n_17_1 1 0 1 NJ 1130
preplace netloc df_o_n_19_1 1 0 1 NJ 750
preplace netloc df_o_n_2_1 1 0 1 NJ 1050
preplace netloc df_o_n_5_1 1 0 1 NJ 930
preplace netloc df_o_n_7_1 1 0 1 NJ 1070
preplace netloc df_o_n_9_1 1 0 1 NJ 730
preplace netloc iob_lvcmos_dut_reg_0_df_0000_n 1 1 2 NJ 770 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0000_p 1 1 2 NJ 790 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0001_p 1 1 2 NJ 810 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0002_p 1 1 2 NJ 1410 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0004_n 1 1 2 NJ 1430 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0004_p 1 1 2 NJ 1450 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0005_n 1 1 2 NJ 830 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0005_p 1 1 2 NJ 850 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0007_p 1 1 2 NJ 1470 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0008_p 1 1 2 NJ 870 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0010_n 1 1 2 NJ 1490 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0010_p 1 1 2 NJ 1510 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0011_n 1 1 2 NJ 890 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0011_p 1 1 2 NJ 910 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0012_p 1 1 2 NJ 930 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0013_n 1 1 2 NJ 950 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0013_p 1 1 2 NJ 970 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0014_p 1 1 2 NJ 1530 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0016_n 1 1 2 NJ 1550 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0016_p 1 1 2 NJ 1570 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0017_p 1 1 2 NJ 990 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0018_p 1 1 2 NJ 1590 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0019_p 1 1 2 NJ 1830 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0020_n 1 1 2 NJ 1850 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0020_p 1 1 2 NJ 1870 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0021_n 1 1 2 NJ 1890 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0021_p 1 1 2 NJ 1910 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0022_n 1 1 2 NJ 1610 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0022_p 1 1 2 NJ 1630 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0023_n 1 1 2 NJ 1010 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0023_p 1 1 2 NJ 1030 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0028_p 1 1 2 NJ 1050 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0029_p 1 1 2 NJ 1650 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0046_n 1 1 2 NJ 1070 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0046_p 1 1 2 NJ 1090 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0048_n 1 1 2 NJ 1670 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0048_p 1 1 2 NJ 1690 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0049_p 1 1 2 NJ 1710 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0050_n 1 1 2 NJ 1730 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0050_p 1 1 2 NJ 1750 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0051_n 1 1 2 NJ 270 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0051_p 1 1 2 NJ 290 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0052_p 1 1 2 NJ 310 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0053_n 1 1 2 NJ 330 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0053_p 1 1 2 NJ 350 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0056_p 1 1 2 NJ 370 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0057_n 1 1 2 NJ 390 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0057_p 1 1 2 NJ 410 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0059_p 1 1 2 NJ 430 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0092_n 1 1 2 NJ 450 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0092_p 1 1 2 NJ 470 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0095_p 1 1 2 NJ 490 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0099_n 1 1 2 NJ 510 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_0099_p 1 1 2 NJ 530 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_n_10 1 1 2 NJ 590 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_n_15 1 1 2 NJ 650 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_n_17 1 1 2 NJ 710 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_5 1 1 2 NJ 570 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_10 1 1 2 NJ 610 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_12 1 1 2 NJ 630 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_15 1 1 2 NJ 670 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_16 1 1 2 NJ 690 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_17 1 1 2 NJ 730 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_20 1 1 2 NJ 130 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_i_p_54 1 1 2 NJ 1770 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_1 1 1 2 NJ 150 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_6 1 1 2 NJ 1130 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_10 1 1 2 NJ 1190 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_12 1 1 2 NJ 1250 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_14 1 1 2 NJ 210 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_16 1 1 2 NJ 1310 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_20 1 1 2 NJ 1370 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_n_57 1 1 2 NJ 1790 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_1 1 1 2 NJ 170 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_2 1 1 2 NJ 1110 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_5 1 1 2 NJ 750 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_6 1 1 2 NJ 1150 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_7 1 1 2 NJ 1170 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_9 1 1 2 NJ 190 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_10 1 1 2 NJ 1210 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_11 1 1 2 NJ 1230 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_12 1 1 2 NJ 1270 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_14 1 1 2 NJ 230 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_15 1 1 2 NJ 1290 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_16 1 1 2 NJ 1330 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_17 1 1 2 NJ 1350 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_19 1 1 2 NJ 250 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_20 1 1 2 NJ 1390 NJ
preplace netloc iob_lvcmos_dut_reg_0_df_o_p_57 1 1 2 NJ 1810 NJ
levelinfo -pg 1 0 140 460 670
pagesize -pg 1 -db -bbox -sgen -120 0 790 1970
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()
cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 
#call make_wrapper to create wrapper files
set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse design_1.bd] -top]
add_files -norecurse -fileset sources_1 $wrapper_path

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvc1902-vsva2197-1MP-e-S -flow {Vivado Synthesis 2022} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2022" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvc1902-vsva2197-1MP-e-S" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvc1902-vsva2197-1MP-e-S -flow {Vivado Implementation 2022} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2022" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvc1902-vsva2197-1MP-e-S" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_device_image.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_device_image.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
