set_property CONFIG_VOLTAGE           1.8           [current_design]
set_property CFGBVS                   GND           [current_design]
#set_property BITSTREAM.CONFIG.PERSIST YES           [current_design]
#set_property CONFIG_MODE              S_SELECTMAP32 [current_design]
#set_property BITSTREAM.CONFIG.USERID 12345678       [current_design]
set_property BITSTREAM.CONFIG.USR_ACCESS deadbeef   [current_design]
#set_property BITSTREAM.CONFIG.CONFIGFALLBACK    ENABLE      [current_design]
set_property PACKAGE_PIN BA19 [get_ports {df_0051_n}];
set_property PACKAGE_PIN BA20 [get_ports {df_0051_p}];
set_property PACKAGE_PIN BG18 [get_ports {df_0052_n}];
set_property PACKAGE_PIN BF18 [get_ports {df_0052_p}];
set_property PACKAGE_PIN BD19 [get_ports {df_0053_n}];
set_property PACKAGE_PIN BE19 [get_ports {df_0053_p}];
set_property PACKAGE_PIN BC36 [get_ports {df_0056_n}];
set_property PACKAGE_PIN BB36 [get_ports {df_0056_p}];
set_property PACKAGE_PIN BF38 [get_ports {df_0057_n}];
set_property PACKAGE_PIN BE37 [get_ports {df_0057_p}];
set_property PACKAGE_PIN BG23 [get_ports {df_0059_n}];
set_property PACKAGE_PIN BF24 [get_ports {df_0059_p}];
set_property PACKAGE_PIN BG19 [get_ports {df_0092_n}];
set_property PACKAGE_PIN BF19 [get_ports {df_0092_p}];
set_property PACKAGE_PIN BF36 [get_ports {df_0095_n}];
set_property PACKAGE_PIN BE36 [get_ports {df_0095_p}];
set_property PACKAGE_PIN BC30 [get_ports {df_0099_n}];
set_property PACKAGE_PIN BC31 [get_ports {df_0099_p}];
set_property PACKAGE_PIN AR17 [get_ports {df_i_n_20}];
set_property PACKAGE_PIN AT16 [get_ports {df_i_p_20}];
set_property PACKAGE_PIN AY39 [get_ports {df_o_n_14}];
set_property PACKAGE_PIN AW39 [get_ports {df_o_p_14}];
set_property PACKAGE_PIN BC38 [get_ports {df_o_n_19}];
set_property PACKAGE_PIN BB38 [get_ports {df_o_p_19}];
set_property PACKAGE_PIN AU36 [get_ports {df_o_n_1}];
set_property PACKAGE_PIN AU37 [get_ports {df_o_p_1}];
set_property PACKAGE_PIN BE22 [get_ports {df_o_n_9}];
set_property PACKAGE_PIN BF23 [get_ports {df_o_p_9}];
#set_property PACKAGE_PIN BA37 [get_ports {df_i_n_21}];
#set_property PACKAGE_PIN AY37 [get_ports {df_i_p_21}];
set_property PACKAGE_PIN AT25 [get_ports {df_0000_n}];
set_property PACKAGE_PIN AT26 [get_ports {df_0000_p}];
set_property PACKAGE_PIN BA27 [get_ports {df_0001_n}];
set_property PACKAGE_PIN BA28 [get_ports {df_0001_p}];
set_property PACKAGE_PIN BG13 [get_ports {df_0005_n}];
set_property PACKAGE_PIN BF14 [get_ports {df_0005_p}];
set_property PACKAGE_PIN BE14 [get_ports {df_0008_n}];
set_property PACKAGE_PIN BE15 [get_ports {df_0008_p}];
set_property PACKAGE_PIN BC15 [get_ports {df_0011_n}];
set_property PACKAGE_PIN BB15 [get_ports {df_0011_p}];
set_property PACKAGE_PIN AV27 [get_ports {df_0012_n}];
set_property PACKAGE_PIN AU28 [get_ports {df_0012_p}];
set_property PACKAGE_PIN BB28 [get_ports {df_0013_n}];
set_property PACKAGE_PIN BB29 [get_ports {df_0013_p}];
set_property PACKAGE_PIN AV25 [get_ports {df_0017_n}];
set_property PACKAGE_PIN AU25 [get_ports {df_0017_p}];
set_property PACKAGE_PIN AU27 [get_ports {df_0023_n}];
set_property PACKAGE_PIN AV26 [get_ports {df_0023_p}];
set_property PACKAGE_PIN AN19 [get_ports {df_0028_n}];
set_property PACKAGE_PIN AN20 [get_ports {df_0028_p}];
set_property PACKAGE_PIN AV21 [get_ports {df_0046_n}];
set_property PACKAGE_PIN AU21 [get_ports {df_0046_p}];
set_property PACKAGE_PIN BE20 [get_ports {df_i_n_10}];
set_property PACKAGE_PIN BE21 [get_ports {df_i_p_10}];
set_property PACKAGE_PIN BF12 [get_ports {df_i_n_12}];
set_property PACKAGE_PIN BE11 [get_ports {df_i_p_12}];
set_property PACKAGE_PIN BG20 [get_ports {df_i_n_15}];
set_property PACKAGE_PIN BF21 [get_ports {df_i_p_15}];
set_property PACKAGE_PIN AN26 [get_ports {df_i_n_16}];
set_property PACKAGE_PIN AM26 [get_ports {df_i_p_16}];
set_property PACKAGE_PIN BF11 [get_ports {df_i_n_17}];
set_property PACKAGE_PIN BG11 [get_ports {df_i_p_17}];
set_property PACKAGE_PIN BD20 [get_ports {df_i_n_5}];
set_property PACKAGE_PIN BC20 [get_ports {df_i_p_5}];
set_property PACKAGE_PIN BD25 [get_ports {df_o_n_5}];
set_property PACKAGE_PIN BC25 [get_ports {df_o_p_5}];
set_property PACKAGE_PIN BC26 [get_ports {df_0002_n}];
set_property PACKAGE_PIN BB26 [get_ports {df_0002_p}];
set_property PACKAGE_PIN BC16 [get_ports {df_0004_n}];
set_property PACKAGE_PIN BB16 [get_ports {df_0004_p}];
set_property PACKAGE_PIN BF32 [get_ports {df_0007_n}];
set_property PACKAGE_PIN BE32 [get_ports {df_0007_p}];
set_property PACKAGE_PIN BG28 [get_ports {df_0010_n}];
set_property PACKAGE_PIN BF29 [get_ports {df_0010_p}];
set_property PACKAGE_PIN BG26 [get_ports {df_0014_n}];
set_property PACKAGE_PIN BF26 [get_ports {df_0014_p}];
set_property PACKAGE_PIN BF28 [get_ports {df_0018_n}];
set_property PACKAGE_PIN BE27 [get_ports {df_0018_p}];
set_property PACKAGE_PIN BE34 [get_ports {df_0022_n}];
set_property PACKAGE_PIN BD33 [get_ports {df_0022_p}];
set_property PACKAGE_PIN AT37 [get_ports {df_0029_n}];
set_property PACKAGE_PIN AT38 [get_ports {df_0029_p}];
set_property PACKAGE_PIN AY23 [get_ports {df_0048_n}];
set_property PACKAGE_PIN AY22 [get_ports {df_0048_p}];
set_property PACKAGE_PIN BB23 [get_ports {df_0049_n}];
set_property PACKAGE_PIN BA23 [get_ports {df_0049_p}];
set_property PACKAGE_PIN BD22 [get_ports {df_0050_n}];
set_property PACKAGE_PIN BC23 [get_ports {df_0050_p}];
set_property PACKAGE_PIN AR27 [get_ports {df_0016_n}];
set_property PACKAGE_PIN AP28 [get_ports {df_0016_p}];
set_property PACKAGE_PIN BE24 [get_ports {df_o_n_10}];
set_property PACKAGE_PIN BE25 [get_ports {df_o_p_10}];
set_property PACKAGE_PIN AU29 [get_ports {df_o_n_11}];
set_property PACKAGE_PIN AT29 [get_ports {df_o_p_11}];
set_property PACKAGE_PIN BD32 [get_ports {df_o_n_12}];
set_property PACKAGE_PIN BE31 [get_ports {df_o_p_12}];
set_property PACKAGE_PIN BG24 [get_ports {df_o_n_15}];
set_property PACKAGE_PIN BG25 [get_ports {df_o_p_15}];
set_property PACKAGE_PIN BB30 [get_ports {df_o_n_16}];
set_property PACKAGE_PIN BB31 [get_ports {df_o_p_16}];
set_property PACKAGE_PIN BD34 [get_ports {df_o_n_17}];
set_property PACKAGE_PIN BD35 [get_ports {df_o_p_17}];
set_property PACKAGE_PIN BF34 [get_ports {df_o_n_20}];
set_property PACKAGE_PIN BE35 [get_ports {df_o_p_20}];
set_property PACKAGE_PIN AN29 [get_ports {df_o_n_2}];
set_property PACKAGE_PIN AM29 [get_ports {df_o_p_2}];
set_property PACKAGE_PIN AT28 [get_ports {df_o_n_6}];
set_property PACKAGE_PIN AR29 [get_ports {df_o_p_6}];
set_property PACKAGE_PIN BD29 [get_ports {df_o_n_7}];
set_property PACKAGE_PIN BD30 [get_ports {df_o_p_7}];
set_property PACKAGE_PIN AN28 [get_ports {df_i_n_54}];
set_property PACKAGE_PIN AM27 [get_ports {df_i_p_54}];
set_property PACKAGE_PIN AY27 [get_ports {df_o_n_57}];
set_property PACKAGE_PIN AW27 [get_ports {df_o_p_57}];
set_property PACKAGE_PIN BE29 [get_ports {df_0019_n}];
set_property PACKAGE_PIN BE30 [get_ports {df_0019_p}];
set_property PACKAGE_PIN BG33 [get_ports {df_0020_n}];
set_property PACKAGE_PIN BF33 [get_ports {df_0020_p}];
#set_property PACKAGE_PIN BG34 [get_ports {df_0021_n}];
#set_property PACKAGE_PIN BG35 [get_ports {df_0021_p}];
set_property PACKAGE_PIN BA31 [get_ports {df_i_n_80}];
set_property PACKAGE_PIN AY31 [get_ports {df_i_p_80}];
set_property IOSTANDARD LVCMOS15 [get_ports {df_0000_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0000_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0001_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0001_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0002_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0002_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0004_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0004_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0005_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0005_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0007_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0007_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0008_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0008_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0010_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0010_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0011_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0011_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0012_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0012_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0013_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0013_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0014_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0014_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0016_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0016_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0017_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0017_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0018_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0018_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0019_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0019_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0020_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0020_p}]
#set_property IOSTANDARD LVCMOS15 [get_ports {df_0021_n}]
#set_property IOSTANDARD LVCMOS15 [get_ports {df_0021_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0022_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0022_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0023_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0023_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0028_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0028_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0029_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0029_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0046_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0046_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0048_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0048_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0049_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0049_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0050_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0050_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0051_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0051_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0052_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0052_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0053_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0053_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0056_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0056_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0057_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0057_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0059_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0059_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0092_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0092_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0095_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0095_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0099_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_0099_p}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_10}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_12}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_15}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_16}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_17}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_20}]
#set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_21}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_5}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_n_54}]
set_property IOSTANDARD LVDS15 [get_ports {df_i_p_80}]
set_property IOSTANDARD LVDS15 [get_ports {df_i_n_80}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_10}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_12}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_15}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_16}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_17}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_20}]
#set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_21}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_5}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_i_p_54}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_1}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_10}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_11}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_12}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_14}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_15}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_16}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_17}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_19}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_2}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_20}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_5}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_57}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_6}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_7}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_n_9}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_1}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_10}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_11}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_12}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_14}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_15}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_16}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_17}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_19}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_2}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_20}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_5}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_57}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_6}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_7}]
set_property IOSTANDARD LVCMOS15 [get_ports {df_o_p_9}]
